[package]
name = "riscv2llvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
regex = "1.5.6"
lazy_static = "1.4.0"

[dev-dependencies]
tempfile = "3.3.0"
