[package]
name = "riscv2llvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
regex = "1.5"
lazy_static = "1.4"

[dev-dependencies]
tempfile = "3"
